In [87]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns


In [88]:
df =pd.read_csv('train.txt',sep=';',names=['text','emotion'], header=None)

In [89]:
df.head()

,text,emotion
0,i didnt feel humiliated,sadness
1,i can go from feeling so hopeless to so damned...,sadness
2,im grabbing a minute to post i feel greedy wrong,anger
3,i am ever feeling nostalgic about the fireplac...,love
4,i am feeling grouchy,anger


In [90]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [91]:
unique_emotions=df['emotion'].unique()

In [92]:
emotion_numbers={}
i=0
for emo in unique_emotions:
    emotion_numbers[emo]=i
    i+=1
df['emotion']=df['emotion'].map(emotion_numbers)

In [93]:
emotion_numbers

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [94]:
df['text']=df['text'].str.lower()

In [95]:
import string 
def remove_punctuation(text):
    return text.translate(str.maketrans('','',string.punctuation))
df['text']=df['text'].apply(remove_punctuation)

In [96]:
def remove_numbers(text):
    return text.translate(str.maketrans('','',string.digits))
df['text']=df['text'].apply(remove_numbers)

In [97]:
def remove_emojies(text):
    new=''
    for i in text:
        if i.isascii():
            new+=i
    return new
df['text']=df['text'].apply(remove_emojies)

In [98]:
import nltk

In [99]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [100]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\adity\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\adity\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [101]:
stop_words=set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [102]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [103]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [104]:
X_train=df['text']
y_train=df['emotion']

test_df=pd.read_csv('test.txt',sep=';',names=['text','emotion'], header=None)
X_test=test_df['text']
y_test=test_df['emotion'].map(emotion_numbers)

In [105]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer


In [106]:
bow_vectorizer=CountVectorizer()
X_train_bow=bow_vectorizer.fit_transform(X_train)
X_test_bow=bow_vectorizer.transform(X_test)

In [107]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix
model=MultinomialNB()
model.fit(X_train_bow,y_train)
y_pred=model.predict(X_test_bow)
accuracy=model.score(X_test_bow,y_test)
print('accuracy:',accuracy)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

accuracy: 0.7655
              precision    recall  f1-score   support

           0       0.74      0.94      0.83       581
           1       0.92      0.57      0.70       275
           2       0.95      0.23      0.37       159
           3       0.00      0.00      0.00        66
           4       0.82      0.53      0.64       224
           5       0.74      0.97      0.84       695

    accuracy                           0.77      2000
   macro avg       0.69      0.54      0.56      2000
weighted avg       0.77      0.77      0.73      2000

[[546   2   0   0   4  29]
 [ 66 156   0   0   7  46]
 [ 27   4  36   0   1  91]
 [ 21   0   0   0  13  32]
 [ 59   7   0   0 119  39]
 [ 16   1   2   0   2 674]]


c:\Users\adity\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\adity\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\adity\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

In [108]:
tfidf_vectorizer=TfidfVectorizer()
X_train_tfidf=tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf=tfidf_vectorizer.transform(X_test)


In [110]:
model_tfidf=MultinomialNB()
model_tfidf.fit(X_train_tfidf,y_train)
y_pred=model_tfidf.predict(X_test_tfidf)
accuracy=model_tfidf.score(X_test_tfidf,y_test)
print('accuracy:',accuracy)

accuracy: 0.6485


In [111]:
from sklearn.linear_model import LogisticRegression

In [112]:
model_lr=LogisticRegression()
model_lr.fit(X_train_bow,y_train)
y_pred_lr=model_lr.predict(X_test_bow)
accuracy_lr=model_lr.score(X_test_bow,y_test)   
print('accuracy:',accuracy_lr)

accuracy: 0.8895


c:\Users\adity\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [113]:
model_lr=LogisticRegression()
model_lr.fit(X_train_tfidf,y_train)
y_pred_lr=model_lr.predict(X_test_tfidf)
accuracy_lr=model_lr.score(X_test_tfidf,y_test)   
print('accuracy:',accuracy_lr)

accuracy: 0.8615
